apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appicontester-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: appicontester-production
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:jojobobby/AppIconWebsite.git
    targetRevision: production
    path: k8s/production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 5
