apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arcana-prod
  namespace: argocd
spec:
  destination:
    namespace: arcana-production
    server: https://kubernetes.default.svc
  source:
    path: k8s
    repoURL: git@github.com:jojobobby/Arcana.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
