apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosmic-prod
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cosmic-production
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:jojobobby/Cosmic-LTS.git
    targetRevision: master
    path: k8s
    helm:
      releaseName: cosmic
      valueFiles:
        - values.yaml
        - values.production.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
